In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#reading data
data=pd.read_csv("traindata.csv",parse_dates=['Date'])

In [3]:
#examine data
data.head()

Type       Date         Name Region     Sub-region
0  Safe 2009-01-31  Afghanistan   Asia  Southern Asia
1  Safe 2009-02-28  Afghanistan   Asia  Southern Asia
2  Safe 2009-03-31  Afghanistan   Asia  Southern Asia
3  Safe 2009-04-30  Afghanistan   Asia  Southern Asia
4  Safe 2009-05-31  Afghanistan   Asia  Southern Asia

In [4]:
#examine data type of columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26252 entries, 0 to 26251
Data columns (total 5 columns):
Type          26252 non-null object
Date          26252 non-null datetime64[ns]
Name          26252 non-null object
Region        26252 non-null object
Sub-region    26252 non-null object
dtypes: datetime64[ns](1), object(4)
memory usage: 1.0+ MB


In [5]:
#split the date field into days, months and year
def convert_date(df):
    df['year']=df['Date'].dt.year
    df['month']=df['Date'].dt.month
    df['Date']=df['Date'].dt.day

In [6]:
#pass the dataframe to date function
convert_date(data)

In [7]:
#examine ddata
data.head()

Type  Date         Name Region     Sub-region  year  month
0  Safe    31  Afghanistan   Asia  Southern Asia  2009      1
1  Safe    28  Afghanistan   Asia  Southern Asia  2009      2
2  Safe    31  Afghanistan   Asia  Southern Asia  2009      3
3  Safe    30  Afghanistan   Asia  Southern Asia  2009      4
4  Safe    31  Afghanistan   Asia  Southern Asia  2009      5

In [8]:
#data=data.drop(['Date'],axis=1)
data.head()

Type  Date         Name Region     Sub-region  year  month
0  Safe    31  Afghanistan   Asia  Southern Asia  2009      1
1  Safe    28  Afghanistan   Asia  Southern Asia  2009      2
2  Safe    31  Afghanistan   Asia  Southern Asia  2009      3
3  Safe    30  Afghanistan   Asia  Southern Asia  2009      4
4  Safe    31  Afghanistan   Asia  Southern Asia  2009      5

In [9]:
data=data.values

In [10]:
#preprocess data and encode categories
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

name=LabelEncoder()
data[:,2]=name.fit_transform(data[:,2])
type_disaster=LabelEncoder()
data[:,0]=type_disaster.fit_transform(data[:,0])
region=LabelEncoder()
data[:,3]=region.fit_transform(data[:,3])
subregion=LabelEncoder()
data[:,4]=subregion.fit_transform(data[:,4])


In [11]:
#examine data
data[:5,:]

array([[12, 31, 0, 3, 13, 2009, 1],
       [12, 28, 0, 3, 13, 2009, 2],
       [12, 31, 0, 3, 13, 2009, 3],
       [12, 30, 0, 3, 13, 2009, 4],
       [12, 31, 0, 3, 13, 2009, 5]], dtype=object)

In [12]:
#import packages for Logistic Regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
lr=LogisticRegression()

In [13]:
#split the data for training the model
from sklearn.model_selection import train_test_split
X=data[:22000,1:]
y=data[:22000,0]
y=y.astype(int)
y

array([12, 12, 12, ..., 12, 12, 12])

In [14]:
#X=data[:3604,1:8]
#y=data[:3604,8]
#X
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=42,shuffle=True)
X_train

array([[30, 25, 4, 4, 2009, 11],
       [31, 91, 3, 3, 2018, 3],
       [30, 71, 1, 15, 2009, 6],
       ...,
       [31, 38, 1, 15, 2013, 3],
       [31, 6, 2, 5, 2012, 10],
       [28, 116, 3, 12, 2018, 2]], dtype=object)

In [15]:
#fit the model
lr.fit(X_train,y_train)



LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
#test the model for X_test
newdata=data[22001:,1:]
actual=data[22001:,0]
y_pred = lr.predict(X_test)
yy=pd.DataFrame({'predict':y_pred,
                 'actual':y_test})
#yy[yy['predict']!=yy['actual']]

In [17]:
train_rmse = np.sqrt(((y_test - y_pred) ** 2).mean())
train_rmse

2.0464159356832083

In [18]:
#test the model for rest of data
newdata=data[22001:,1:]
actual=data[22001:,0]
y_pred = lr.predict(newdata)
yy=pd.DataFrame({'predict':y_pred,
                 'actual':actual})
#yy[yy['predict']!=yy['actual']]

In [19]:
#error
train_rmse = np.sqrt(((actual - y_pred) ** 2).mean())
train_rmse

1.8332638296527726

In [19]:
#now test the model for new data
testdata=pd.read_csv("testdata.csv",parse_dates=['Date'])

In [20]:
testdata.head()

Date   Name Region     Sub-region
0 2020-01-31  Nepal   Asia  Southern Asia
1 2020-02-08  Nepal   Asia  Southern Asia
2 2020-03-03  Nepal   Asia  Southern Asia
3 2020-04-02  Nepal   Asia  Southern Asia
4 2020-05-29  Nepal   Asia  Southern Asia

In [21]:
testdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2304 entries, 0 to 2303
Data columns (total 4 columns):
Date          2304 non-null datetime64[ns]
Name          2304 non-null object
Region        2304 non-null object
Sub-region    2304 non-null object
dtypes: datetime64[ns](1), object(3)
memory usage: 72.1+ KB


In [22]:
def convert_date(df):
    df['year']=df['Date'].dt.year
    df['month']=df['Date'].dt.month
    df['Date']=df['Date'].dt.day
convert_date(testdata)

In [23]:
testdata.head()

Date   Name Region     Sub-region  year  month
0    31  Nepal   Asia  Southern Asia  2020      1
1     8  Nepal   Asia  Southern Asia  2020      2
2     3  Nepal   Asia  Southern Asia  2020      3
3     2  Nepal   Asia  Southern Asia  2020      4
4    29  Nepal   Asia  Southern Asia  2020      5

In [24]:
#testdata=testdata.drop(['Date'],axis=1)
testdata.head()

Date   Name Region     Sub-region  year  month
0    31  Nepal   Asia  Southern Asia  2020      1
1     8  Nepal   Asia  Southern Asia  2020      2
2     3  Nepal   Asia  Southern Asia  2020      3
3     2  Nepal   Asia  Southern Asia  2020      4
4    29  Nepal   Asia  Southern Asia  2020      5

In [25]:
testdata=testdata.values

In [26]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

name=LabelEncoder()
testdata[:,1]=name.fit_transform(testdata[:,1])
region=LabelEncoder()
testdata[:,2]=region.fit_transform(testdata[:,2])
subregion=LabelEncoder()
testdata[:,3]=subregion.fit_transform(testdata[:,3])


In [27]:
testdata[:5,]

array([[31, 118, 2, 12, 2020, 1],
       [8, 118, 2, 12, 2020, 2],
       [3, 118, 2, 12, 2020, 3],
       [2, 118, 2, 12, 2020, 4],
       [29, 118, 2, 12, 2020, 5]], dtype=object)

In [28]:
y_pred = lr.predict(testdata)


In [29]:
output=pd.DataFrame({'prediction':y_pred})

#yy.loc[yy.yyy >=0.75, 'yyy'] = 1
#yy.loc[yy.yyy <0.75, 'yyy'] = 0
output['prediction'].value_counts()

6     1577
12     498
17     226
4        2
0        1
Name: prediction, dtype: int64

In [30]:
test=pd.read_csv("testdata.csv",parse_dates=['Date'])
test['output']=output['prediction']

In [31]:
def convert_date(df):
    df['DAY_OF_WEEK']=df['Date'].dt.dayofweek
    df['MONTH']=df['Date'].dt.month
    df['DAY_OF_MONTH']=df['Date'].dt.day
    #df['YEAR']=df['Date'].dt.year
    

convert_date(test)

In [32]:
test.head()

Date   Name Region     Sub-region  output  DAY_OF_WEEK  MONTH  \
0 2020-01-31  Nepal   Asia  Southern Asia      12            4      1   
1 2020-02-08  Nepal   Asia  Southern Asia       6            5      2   
2 2020-03-03  Nepal   Asia  Southern Asia       6            1      3   
3 2020-04-02  Nepal   Asia  Southern Asia       6            3      4   
4 2020-05-29  Nepal   Asia  Southern Asia      12            4      5   

   DAY_OF_MONTH  
0            31  
1             8  
2             3  
3             2  
4            29

In [33]:
test.to_csv("Disaster-prediction.csv")

In [34]:
a1=list(subregion.classes_)
a1

['Australia and New Zealand',
 'Central Asia',
 'Eastern Asia',
 'Eastern Europe',
 'Latin America and the Caribbean',
 'Melanesia',
 'Micronesia',
 'Northern Africa',
 'Northern America',
 'Northern Europe',
 'Polynesia',
 'South-eastern Asia',
 'Southern Asia',
 'Southern Europe',
 'Sub-Saharan Africa',
 'Western Asia',
 'Western Europe']

In [37]:
reference=pd.DataFrame({'class':a1})
reference

class
0         Australia and New Zealand
1                      Central Asia
2                      Eastern Asia
3                    Eastern Europe
4   Latin America and the Caribbean
5                         Melanesia
6                        Micronesia
7                   Northern Africa
8                  Northern America
9                   Northern Europe
10                        Polynesia
11               South-eastern Asia
12                    Southern Asia
13                  Southern Europe
14               Sub-Saharan Africa
15                     Western Asia
16                   Western Europe

In [38]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib
print('Libraries Imported')

Libraries Imported


/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [39]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [40]:
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [50]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = classifier.predict(testdata)

output=pd.DataFrame({'prediction':y_pred})
output['prediction'].value_counts()

12    2304
Name: prediction, dtype: int64

In [51]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train) 
y_pred= dtree_model.predict(testdata) 

output=pd.DataFrame({'prediction':y_pred})
output['prediction'].value_counts()

12    2304
Name: prediction, dtype: int64

In [52]:
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(testdata) 
  
output=pd.DataFrame({'prediction':svm_predictions})
output['prediction'].value_counts()

12    2294
14      10
Name: prediction, dtype: int64